#!/bin/bash
#SBATCH --job-name=pgap_annotation
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=32G

netID=yourNetID
outdir=output_directory
genome=input_fasta
species=species_orgenus_name
containerName=pgap_2023-10-03.build7061.sif

export PGAP_INPUT_DIR=/scratch/netID

/scratch/netID/pgap.py -o /scratch/netID/output_directory/ -g /scratch/netID/genome -s 'species' -c 2 -r -D singularity --container-name /scratch/netID/containerName --no-self-update
